import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  date,
  index,
  integer,
  numeric,
  pgTable,
  smallint,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { authUsers, tenants } from "./core";
import { contacts } from "./contacts";

/**
 * A property (listing) owned by a tenant. `internalCode` is generated by
 * `generatePropertyCode` (T1.7) as `${tenantId.slice(0, 8)}-${sequential}` and is unique per
 * tenant (not globally). `ownerContactId` is a required FK into `contacts` — see ADR-011 in
 * `docs/decisiones.md` for why `contacts` was created ahead of its own task (T1.1) to support it.
 */
export const properties = pgTable(
  "properties",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    internalCode: text("internal_code").notNull(),
    propertyType: text("property_type").notNull(),
    operationType: text("operation_type").notNull(),
    status: text("status").notNull().default("disponible"),
    ownerContactId: uuid("owner_contact_id")
      .notNull()
      .references(() => contacts.id),
    /** COP, whole pesos. Set when `operationType` is `venta` or `ambas`. */
    salePriceCop: bigint("sale_price_cop", { mode: "number" }),
    /** COP, whole pesos. Set when `operationType` is `arriendo` or `ambas`. */
    monthlyRentCop: bigint("monthly_rent_cop", { mode: "number" }),
    areaM2: integer("area_m2"),
    bedrooms: smallint("bedrooms"),
    bathrooms: smallint("bathrooms"),
    parkingSpots: smallint("parking_spots"),
    /** Colombian socioeconomic stratum, 1–6. */
    stratum: smallint("stratum"),
    ageYears: smallint("age_years"),
    /** Never shown on the public listing page (`/p/[tenant]/[codigo]`, T1.10) — agent-only. */
    privateAddress: text("private_address"),
    /** Public: shown on the public listing page. */
    neighborhood: text("neighborhood"),
    city: text("city"),
    department: text("department"),
    lat: numeric("lat", { precision: 9, scale: 6 }),
    lng: numeric("lng", { precision: 9, scale: 6 }),
    /** "Matrícula inmobiliaria" — private, never shown publicly. */
    registrationNumber: text("registration_number"),
    exclusivity: boolean("exclusivity").notNull().default(false),
    exclusivityUntil: date("exclusivity_until"),
    /** e.g. `3.00` for 3%. */
    commissionPercentage: numeric("commission_percentage", { precision: 5, scale: 2 }),
    description: text("description"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid("created_by").references(() => authUsers.id),
  },
  (table) => [
    unique("properties_tenant_internal_code_unique").on(table.tenantId, table.internalCode),
    index("properties_tenant_id_idx").on(table.tenantId, table.id),
    index("properties_tenant_status_idx").on(table.tenantId, table.status),
    index("properties_tenant_type_operation_idx").on(
      table.tenantId,
      table.propertyType,
      table.operationType,
    ),
    index("properties_tenant_created_idx").on(table.tenantId, table.createdAt.desc()),
    index("properties_tenant_owner_idx").on(table.tenantId, table.ownerContactId),
    check(
      "properties_property_type_check",
      sql`${table.propertyType} in ('apartamento', 'casa', 'lote', 'local', 'oficina', 'bodega', 'finca')`,
    ),
    check(
      "properties_operation_type_check",
      sql`${table.operationType} in ('venta', 'arriendo', 'ambas')`,
    ),
    check(
      "properties_status_check",
      sql`${table.status} in ('disponible', 'reservada', 'vendida', 'arrendada', 'inactiva')`,
    ),
    check(
      "properties_stratum_check",
      sql`${table.stratum} is null or (${table.stratum} between 1 and 6)`,
    ),
    check(
      "properties_sale_price_non_negative_check",
      sql`${table.salePriceCop} is null or ${table.salePriceCop} >= 0`,
    ),
    check(
      "properties_monthly_rent_non_negative_check",
      sql`${table.monthlyRentCop} is null or ${table.monthlyRentCop} >= 0`,
    ),
  ],
);

/**
 * Ordered photos/videos of a property, stored in Supabase Storage (bucket `property-photos`, path
 * `{tenantId}/{propertyId}/{filename}` — see the storage migration and ADR-011). Exactly one row
 * per property may have `isCover = true`; enforced by the
 * `property_media_enforce_single_cover` trigger, not by a SQL constraint (Postgres has no
 * portable "unique where true" partial-unique-per-group primitive that also auto-demotes the
 * previous cover on insert/update).
 */
export const propertyMedia = pgTable(
  "property_media",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    mediaType: text("media_type").notNull(),
    sortOrder: smallint("sort_order").notNull().default(0),
    isCover: boolean("is_cover").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("property_media_tenant_property_order_idx").on(
      table.tenantId,
      table.propertyId,
      table.sortOrder,
    ),
    check("property_media_type_check", sql`${table.mediaType} in ('foto', 'video')`),
  ],
);

/**
 * Private documents attached to a property (title certificates, powers of attorney, etc.), stored
 * in the same `property-photos` bucket under `{tenantId}/{propertyId}/documents/{filename}` —
 * never publicly readable regardless of the property's `status`.
 */
export const propertyDocuments = pgTable(
  "property_documents",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    documentType: text("document_type"),
    url: text("url").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("property_documents_tenant_property_idx").on(table.tenantId, table.propertyId),
    check(
      "property_documents_type_check",
      sql`${table.documentType} is null or ${table.documentType} in ('tradicion_libertad', 'paz_salvos', 'poder', 'otro')`,
    ),
  ],
);

export type Property = typeof properties.$inferSelect;
export type NewProperty = typeof properties.$inferInsert;
export type PropertyMedia = typeof propertyMedia.$inferSelect;
export type NewPropertyMedia = typeof propertyMedia.$inferInsert;
export type PropertyDocument = typeof propertyDocuments.$inferSelect;
export type NewPropertyDocument = typeof propertyDocuments.$inferInsert;
